/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.io.File;
import java.text.Normalizer;
import jpl.Query;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import jpl.*;
/**
 *
 * @author Guilherme Ricarte
 */
public class Perguntar extends javax.swing.JFrame {

    /**
     * Creates new form Perguntar
     */
    public Perguntar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pessoa = new javax.swing.JTextField();
        perguntar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sel_parentesco = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Perguntar?");
        setBounds(new java.awt.Rectangle(530, 250, 0, 0));

        pessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoa(evt);
            }
        });

        perguntar.setText("Perguntar");
        perguntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perguntar(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });

        jLabel1.setText("Pessoa:");

        sel_parentesco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Irmãs de", "Irmãos de", "Avós de", "Avôs de" }));
        sel_parentesco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel_parentesco(evt);
            }
        });

        jLabel3.setText("Parentesco:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Preencha as informações necessarias: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sel_parentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(perguntar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sel_parentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perguntar)
                    .addComponent(cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static String removeAcentos(String str) {
        str = Normalizer.normalize(str, Normalizer.Form.NFD);
        str = str.replaceAll("[^\\p{ASCII}]", "");
        return str;
    }
    private void pessoa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoa
        // TODO add your handling code here:
    }//GEN-LAST:event_pessoa

    private void sel_parentesco(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel_parentesco
        // TODO add your handling code here:
    }//GEN-LAST:event_sel_parentesco

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        this.dispose();
    }//GEN-LAST:event_cancelar

    private void perguntar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perguntar
        new File("src/files/resposta_prolog.xml").delete();
        if (!pessoa.getText().isEmpty()) {
            String t1 = "consult('src/files/banco_de_dados.pl')";
            Query q1 = new Query(t1);
            q1.hasSolution();
            String escolha_predicado = removeAcentos(sel_parentesco.getSelectedItem().toString().toLowerCase().replace(" ", "_").toLowerCase());
            String t4;
            Query q4 = null;
            String arquivo = "('C:/Users/Guilherme Ricarte/Documents/GitHub/ProjetoPLP/src/files/resposta_prolog.xml'";
            switch(escolha_predicado) {
                case "irmaos_de":
                    t4 = "cria_irmaos_de" + arquivo + "," + this.pessoa.getText().trim() + ",Y).";
                    q4 = new Query(t4); 
                    break;
                case "irmas_de":
                    t4 = "cria_irmas_de" + arquivo + "," + this.pessoa.getText().trim() + ",Y).";
                    q4 = new Query(t4); 
                    break;
                case "avos_de":
                    t4 = "cria_avos_de" + arquivo + "," + this.pessoa.getText().trim() + ",Y).";
                    q4 = new Query(t4); 
                    break;
                case "avohs_de":
                    t4 = "cria_avohs_de" + arquivo + "," + this.pessoa.getText().trim() + ",Y).";
                    q4 = new Query(t4); 
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "ERRO, por favor verifique !", "Erro", JOptionPane.PLAIN_MESSAGE);

            }
            while ( q4.hasMoreSolutions() ){
                java.util.Hashtable s4= q4.nextSolution();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Campo inválido ou vázio, por favor verifique !", "Erro", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_perguntar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perguntar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perguntar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perguntar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perguntar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Perguntar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton perguntar;
    private javax.swing.JTextField pessoa;
    private javax.swing.JComboBox sel_parentesco;
    // End of variables declaration//GEN-END:variables
}
